- hosts: localhost
  connection: local

  tasks:
  - name: Create & Start Container
  docker_container:
    name: myweb
    image: "swethom3143/tomcat-application:{{ lookup('env','BUILD_NUMBER') }}"
    state: started
    ports:
        - "80:8080"